nft_data = [
    {
        'artwotk_name': '001',
        'media': '001.png',
        'artist': 'Georgi Chertovskee',
        'collection': 'KODA CANARY',
        'edition': '1/1',
        'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
        'qr_code': 'qr001.png',
        'qr_folder': '../nft_submissions/Chertovskee',
        'nft_folder': '../nft_submissions/Chertovskee/NFTs',
    },
    {
        'artwotk_name': '002',
        'media': '002.png',
        'artist': 'Georgi Chertovskee',
        'collection': 'KODA CANARY',
        'edition': '1/1',
        'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
        'qr_code': 'qr002.png',
        'qr_folder': '../nft_submissions/Chertovskee',
        'nft_folder': '../nft_submissions/Chertovskee/NFTs',
    },
    {
        'artwotk_name': '003',
        'media': '003.png',
        'artist': 'Georgi Chertovskee',
        'collection': 'KODA CANARY',
        'edition': '1/1',
        'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
        'qr_code': 'qr003.png',
        'qr_folder': '../nft_submissions/Chertovskee',
        'nft_folder': '../nft_submissions/Chertovskee/NFTs',
    },

]

#  {
#         'artwotk_name': '002',
#         'media': '002.png',
#         'artist': 'Georgi Chertovskee',
#         'collection': 'KODA CANARY',
#         'edition': '1/1',
#         'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
#         'qr_code': 'qr002.png',
#     },
#     {
#         'artwotk_name': '003',
#         'media': '003.png',
#         'artist': 'Georgi Chertovskee',
#         'collection': 'KODA CANARY',
#         'edition': '1/1',
#         'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
#         'qr_code': 'qr003.png',
#     },
#     {
#         'artwotk_name': '004',
#         'media': '004.png',
#         'artist': 'Georgi Chertovskee',
#         'collection': 'KODA CANARY',
#         'edition': '1/1',
#         'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
#         'qr_code': 'qr004.png',
#     },
#     {
#         'artwotk_name': '005',
#         'media': '005.png',
#         'artist': 'Georgi Chertovskee',
#         'collection': 'KODA CANARY',
#         'edition': '1/1',
#         'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
#         'qr_code': 'qr005.png',
#     },
#     {
#         'artwotk_name': '006',
#         'media': '006.png',
#         'artist': 'Georgi Chertovskee',
#         'collection': 'KODA CANARY',
#         'edition': '1/1',
#         'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
#         'qr_code': 'qr006.png',
#     },
#     {
#         'artwotk_name': '007',
#         'media': '007.png',
#         'artist': 'Georgi Chertovskee',
#         'collection': 'KODA CANARY',
#         'edition': '1/1',
#         'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
#         'qr_code': 'qr007.png',
#     },
#     {
#         'artwotk_name': '008',
#         'media': '008.png',
#         'artist': 'Georgi Chertovskee',
#         'collection': 'KODA CANARY',
#         'edition': '1/1',
#         'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
#         'qr_code': 'qr008.png',
#     },
#     {
#         'artwotk_name': '009',
#         'media': '009.png',
#         'artist': 'Georgi Chertovskee',
#         'collection': 'KODA CANARY',
#         'edition': '1/1',
#         'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
#         'qr_code': 'qr009.png',
#     },
#     {
#         'artwotk_name': '010',
#         'media': '010.png',
#         'artist': 'Georgi Chertovskee',
#         'collection': 'KODA CANARY',
#         'edition': '1/1',
#         'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
#         'qr_code': 'qr010.png',
#     },
#     {
#         'artwotk_name': '011',
#         'media': '011.png',
#         'artist': 'Georgi Chertovskee',
#         'collection': 'KODA CANARY',
#         'edition': '1/1',
#         'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
#         'qr_code': 'qr011.png',
#     },
#     {
#         'artwotk_name': '012',
#         'media': '012.png',
#         'artist': 'Georgi Chertovskee',
#         'collection': 'KODA CANARY',
#         'edition': '1/1',
#         'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
#         'qr_code': 'qr012.png',
#     },
#     {
#         'artwotk_name': '013',
#         'media': '013.png',
#         'artist': 'Georgi Chertovskee',
#         'collection': 'KODA CANARY',
#         'edition': '1/1',
#         'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
#         'qr_code': 'qr013.png',
#     },
#     {
#         'artwotk_name': '014',
#         'media': '014.png',
#         'artist': 'Georgi Chertovskee',
#         'collection': 'KODA CANARY',
#         'edition': '1/1',
#         'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
#         'qr_code': 'qr014.png',
#     },
#     {
#         'artwotk_name': '015',
#         'media': '015.png',
#         'artist': 'Georgi Chertovskee',
#         'collection': 'KODA CANARY',
#         'edition': '1/1',
#         'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
#         'qr_code': 'qr015.png',
#     }
