nft_data = {
    'Georgi Chertovskee': {
        'qr_folder': '../nft_submissions/Chertovskee',
        'media_folder': '../nft_submissions/Chertovskee/NFTs',
        'nft_data': [
            {
                'artwork_name': '001',
                'media': '001.png',
                'artist': 'Georgi Chertovskee',
                'collection': 'KODA CANARY',
                'edition': '1/1',
                'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
                'qr_code': 'qr001.png',
                'qr_folder': '../nft_submissions/Chertovskee',
                'nft_folder': '../nft_submissions/Chertovskee/NFTs',
            },
            {
                'artwork_name': '002',
                'media': '002.png',
                'artist': 'Georgi Chertovskee',
                'collection': 'KODA CANARY',
                'edition': '1/1',
                'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
                'qr_code': 'qr002.png',
                'qr_folder': '../nft_submissions/Chertovskee',
                'nft_folder': '../nft_submissions/Chertovskee/NFTs',
            },
            {
                'artwork_name': '003',
                'media': '003.png',
                'artist': 'Georgi Chertovskee',
                'collection': 'KODA CANARY',
                'edition': '1/1',
                'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
                'qr_code': 'qr003.png',
                'qr_folder': '../nft_submissions/Chertovskee',
                'nft_folder': '../nft_submissions/Chertovskee/NFTs',
            },

            {
                'artwork_name': '004',
                'media': '004.png',
                'artist': 'Georgi Chertovskee',
                'collection': 'KODA CANARY',
                'edition': '1/1',
                'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
                'qr_code': 'qr004.png',
                'qr_folder': '../nft_submissions/Chertovskee',
                'nft_folder': '../nft_submissions/Chertovskee/NFTs',
            },
            {
                'artwork_name': '005',
                'media': '005.png',
                'artist': 'Georgi Chertovskee',
                'collection': 'KODA CANARY',
                'edition': '1/1',
                'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
                'qr_code': 'qr005.png',
                'qr_folder': '../nft_submissions/Chertovskee',
                'nft_folder': '../nft_submissions/Chertovskee/NFTs',
            },
            {
                'artwork_name': '006',
                'media': '006.png',
                'artist': 'Georgi Chertovskee',
                'collection': 'KODA CANARY',
                'edition': '1/1',
                'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
                'qr_code': 'qr006.png',
                'qr_folder': '../nft_submissions/Chertovskee',
                'nft_folder': '../nft_submissions/Chertovskee/NFTs',
            },
            {
                'artwork_name': '007',
                'media': '007.png',
                'artist': 'Georgi Chertovskee',
                'collection': 'KODA CANARY',
                'edition': '1/1',
                'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
                'qr_code': 'qr007.png',
                'qr_folder': '../nft_submissions/Chertovskee',
                'nft_folder': '../nft_submissions/Chertovskee/NFTs',
            },
            {
                'artwork_name': '008',
                'media': '008.png',
                'artist': 'Georgi Chertovskee',
                'collection': 'KODA CANARY',
                'edition': '1/1',
                'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
                'qr_code': 'qr008.png',
                'qr_folder': '../nft_submissions/Chertovskee',
                'nft_folder': '../nft_submissions/Chertovskee/NFTs',
            },
            {
                'artwork_name': '009',
                'media': '009.png',
                'artist': 'Georgi Chertovskee',
                'collection': 'KODA CANARY',
                'edition': '1/1',
                'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
                'qr_code': 'qr009.png',
                'qr_folder': '../nft_submissions/Chertovskee',
                'nft_folder': '../nft_submissions/Chertovskee/NFTs',
            },
            {
                'artwork_name': '010',
                'media': '010.png',
                'artist': 'Georgi Chertovskee',
                'collection': 'KODA CANARY',
                'edition': '1/1',
                'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
                'qr_code': 'qr010.png',
                'qr_folder': '../nft_submissions/Chertovskee',
                'nft_folder': '../nft_submissions/Chertovskee/NFTs',
            },
            {
                'artwork_name': '011',
                'media': '011.png',
                'artist': 'Georgi Chertovskee',
                'collection': 'KODA CANARY',
                'edition': '1/1',
                'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
                'qr_code': 'qr011.png',
                'qr_folder': '../nft_submissions/Chertovskee',
                'nft_folder': '../nft_submissions/Chertovskee/NFTs',
            },
            {
                'artwork_name': '012',
                'media': '012.png',
                'artist': 'Georgi Chertovskee',
                'collection': 'KODA CANARY',
                'edition': '1/1',
                'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
                'qr_code': 'qr012.png',
                'qr_folder': '../nft_submissions/Chertovskee',
                'nft_folder': '../nft_submissions/Chertovskee/NFTs',
            },
            {
                'artwork_name': '013',
                'media': '013.png',
                'artist': 'Georgi Chertovskee',
                'collection': 'KODA CANARY',
                'edition': '1/1',
                'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
                'qr_code': 'qr013.png',
                'qr_folder': '../nft_submissions/Chertovskee',
                'nft_folder': '../nft_submissions/Chertovskee/NFTs',
            },
            {
                'artwork_name': '014',
                'media': '014.png',
                'artist': 'Georgi Chertovskee',
                'collection': 'KODA CANARY',
                'edition': '1/1',
                'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
                'qr_code': 'qr014.png',
                'qr_folder': '../nft_submissions/Chertovskee',
                'nft_folder': '../nft_submissions/Chertovskee/NFTs',
            },
            {
                'artwork_name': '015',
                'media': '015.png',
                'artist': 'Georgi Chertovskee',
                'collection': 'KODA CANARY',
                'edition': '1/1',
                'description': 'This canaries embodies author’s unique perspective on the contemporary world. Each card serves as a time capsule, capturing the essence of this era\'s artistic expression, wit, and cultural nuances. As future collectors peruse these pieces, they will witness a visual representation of the spirit of our times.',
                'qr_code': 'qr015.png',
                'qr_folder': '../nft_submissions/Chertovskee',
                'nft_folder': '../nft_submissions/Chertovskee/NFTs',
            }

        ]
    }}
